### PR TITLE
Fixes memory storage returning keys in list, not value

### PR DESCRIPTION
**Pull request by JosephSalisbury**
This helps sharpen up https://github.com/giantswarm/ipam/pull/2

### CODE REVIEW

**Comment by JosephSalisbury** [comment]
I know you're probably doing this in a much better way, I just need this fixed to move forwards with the ipam service.

**Comment by JosephSalisbury** [comment]
Oh, `List` should actually return keys?

**Comment by kopiczko** [comment]
Yes: https://github.com/giantswarm/microkit/blob/master/storage/etcd/service_integration_test.go#L46-L78

But only nested ones?

**Comment by kopiczko** [comment]
But still it returns absolute path in memory implementation and relative path in etcd impl.

**Comment by JosephSalisbury** [comment]
@kopiczko have a look again. Returning the relative path here. Basically just a test addition now :D

**Comment by kopiczko** [comment]
No, sorry it's compatible across implementations. And should stay that way IMO.

If you need a value you should:

```
var key string
list, _ := storage.List(ctx, key)
storage.Search(ctx, key+list[0])
```

**Comment by kopiczko** [comment]
Aslo `Storage.List` godoc has to be fixed.

**Comment by JosephSalisbury** [comment]
Yeah, this feels right now. Good to get it verified.

**Pull request merged**
